spring.application.name=spring-production-ready

spring.datasource.url=jdbc:mysql://localhost:3306/prodFeature
spring.datasource.username=root
spring.datasource.password=Riddhi@10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# add data with the help of hibernate also
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
server.port= 9000
employeeService.base.url=http://localhost:8080